#!/bin/bash

#quoted_args="$(printf " %q" "${@}")"

FORM=`yad --borders=20 --title="Временная метка" --text-align=center --form --separator="," --item-separator="|" \
	--field=:LBL --field="Оставить оригинальный файл:CHK" \
			"" 					TRUE`

if [ $? = 0 ]
	then
		copy=$( echo $FORM | awk -F ',' '{print $2}')

		for file in "$@"
			do
				sufix=`date +%Y-%m-%d_%H-%M-%S`
				newname="${file%.*}_${sufix}.${file##*.}"
				if [ $copy == TRUE ]
					then
					cp "$file" "$newname"
				else
					mv "$file" "$newname"
				fi
				#notify-send -t 10000 -i "gtk-ok" "123" "$newname"
		done
fi



