#!/bin/bash

path_to_save="$1"														# Выбранный каталог для загрузки

file_name1="%(title)s.%(ext)s"											# Имя файла для сохранения
file_name2="%\(title\)s.%\(ext\)s"										# Имя файла для сохранения после ввода кода формата

clipboard=`xclip -sel clip -o`											# Присвоить переменной path содержимое буфера обмена

if [[ -z `echo $clipboard | grep "youtu"` ]]
	then
		notify-send -t 10000 -i "gtk-error" "youtube-dl" "Буфер обмена не содержит ссылку на YouTube"
		exit
elif [[ `echo $clipboard | grep "https://"` ]]							# Корректировка ссылки. Добавить "https://"
	then url=$clipboard
	else url="https://"$clipboard
fi

link=${url/"›"/"/"}														# Корректировка ссылки. Убрать символ ">"

# Вывод формы
parameters=`yad --focus-field=4 --borders=20 --width=600 --title="Youtube-dl" --text="Скачать видео" \
	--button="Скачать:0" \
	--button="Список форматов:5" \
	--button="Отмена:1" \
	--text-align=center --item-separator="|" --form \
	--field=" :LBL" --field="Ссылка:RO"			--field="Выбор качества:CB" 				--field="Каталог для сохранения:DIR" --field="Скачать только обложку:CHK" --field=" :LBL" --field="Скачать отрезок:LBL" --field="Начало (1:00):CE" --field="Длительность, сек" --field=" :LBL" \
		""				"$link"		"best|bestvideo|bestaudio|worst|worstvideo|worstaudio"			"${path_to_save}"						FLASE							""						""							""							10`

exit_status=$?

quality=$( echo $parameters | awk -F '|' '{print $3}')					# Выбор качества видео
dir=$( echo $parameters | awk -F '|' '{print $4}')						# Каталог для сохранения файла ($path_to_save)
thumbnail=$( echo $parameters | awk -F '|' '{print $5}')				# Скачать только обложку
start=$( echo $parameters | awk -F '|' '{print $8}')					# Время начала отрезка
duration=$( echo $parameters | awk -F '|' '{print $9}')					# Длительность

if [ "$exit_status" = 0 ]												# Закачка
   then
		if [ $thumbnail = TRUE ]										# Скачать только обложку
			then
				gnome-terminal --title="youtube-dl" --geometry=70x6 --hide-menubar \
					-e "youtube-dl --console-title --write-thumbnail --skip-download --output \"$dir/${file_name1}\" $link"
				
		elif [ -z $start ]
			then
				gnome-terminal --title="youtube-dl" --geometry=70x6 --hide-menubar \
					-e "youtube-dl --console-title --continue --output \"$dir/${file_name1}\" --format $quality $link"
			else
				sufix="${start/:/-}_${duration/:/-}"
				file_name3=`youtube-dl --get-filename "$link"`
				ffmpeg -y $(youtube-dl -g "$link" | sed "s/.*/-ss $start -i &/") -t $duration -c copy "$dir/${file_name3}_$sufix.mkv"
		fi
fi

if [ "$exit_status" = 5 ]												# Получение списка и загрузка по коду
	then 
		gnome-terminal --wait --title="youtube-dl - $link" --geometry=120x26 --hide-menubar \
		-e "bash -c \"youtube-dl -F $link; echo; echo $link; echo; echo -n \"\"Введите format code для загрузки:\ \"\"; read format; echo \$format; youtube-dl --console-title --continue --output $dir/$file_name2 --format \$format \"$link\"; read\""
fi
