#!/bin/sh

# Адрес папки для скачивания
destination="$PWD/$1"

# Присвоить переменной path содержимое буфера обмена
path=`xclip -sel clip -o`

#Получить размер файла
size=`HEAD -t 5 $path | grep '^Content-Length:' | sed s/"Content-Length: "//g | perl -pe 's/(?<=\d)(?=(?:\d\d\d)+(?: |_|$))/ /g'`

#Получить имя файла
filename=${path##*/}

# Вызвать запрос с вводом адреса
link=`zenity --entry --title="wget" --width=600 --text="Скачать файл $filename \nс размером $size байт \nв каталог $destination" --entry-text=$path --ok-label="Скачать"`

# Запуск утилиты wget
if [ $? = 0 ]
	then
		gnome-terminal --geometry=90x15 --hide-menubar --title "wget $filename" -e "wget --random-wait --user-agent='Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 OPR/39.0.2256.71' -c -P \"$destination\" \"$link\""

		notify-send -i "gtk-ok" "wget" "Завершена загрузка файла:\n\"$link\"\nв каталог \"$destination\""
fi
