#!/bin/bash

if [ "$1" ]
	then dir_to_save="$1"																# Выбранный каталог для загрузки
	else dir_to_save="$PWD"
fi

user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36"

if [ "$2" ]
	then link="$2"
	else link=`xclip -sel clip -o`													# Присвоить переменной содержимое буфера обмена
fi

# Получить размер файла
size_byte=`HEAD -t 5 "$link" | grep '^Content-Length:' | sed s/"Content-Length: "//g`
size=`echo $size_byte | perl -pe 's/(?<=\d)(?=(?:\d\d\d)+(?: |_|$))/ /g'`

# Получить имя файла
filename=${link##*/}

# Вывод формы
parameters=`yad --borders=20 --width=800 --title="wget" --text="Скачать файл" \
	--text-align=center --item-separator="|" --form \
	--field=" :LBL"		--field="Ссылка:RO"		--field="Имя:RO"	--field="Размер, байт:RO"	--field="Продолжить загрузку:CHK" --field="Каталог для сохранения:DIR" \
			""								"$link"				"$filename"					"$size"									"TRUE"							"$dir_to_save" `

exit_status=$?

if [ "$exit_status" == 0 ]
	then
		continue=$( echo $parameters | awk -F '|' '{print $5}')				# Продолжить загрузку файла
		if [ "$continue" == "TRUE" ]
			then continue="--continue"
			else continue=""
		fi

		dir=$( echo $parameters | awk -F '|' '{print $6}')						# Каталог для сохранения файла ($path_to_save)
		path_tmp="${dir}/${filename}.wget-tmp"
		echo "$link" > "$path_tmp"														# Сохранить ссылку во временный файл
	
		gnome-terminal --wait --geometry=90x5 --hide-menubar --title "wget $filename" \
			-- bash -c "wget --no-verbose --show-progress --random-wait --user-agent=\"$user_agent\" $continue -P \"$dir\" \"$link\""

		size_received=`stat -c %s "${dir}/${filename}"`
		if [ $size_received == $size_byte ]
			then
				rm --force "$path_tmp"
				notify-send -i "gtk-ok" "wget" "Завершена загрузка файла:\n\"$link\"\n\nв каталог:\n\"$dir\""
			else
				notify-send -i "error" "wget" "Загрузка файла $filename не завершена"
		fi
fi
