#!/bin/bash

if [ "$1" ]
	then path_to_save="$1"																# Выбранный каталог для загрузки
	else path_to_save="$PWD"
fi

file_name1="%(title)s.%(ext)s"														# Имя файла для сохранения
file_name2="%\(title\)s.%\(ext\)s"													# Имя файла для сохранения после ввода кода формата

clipboard=`xclip -sel clip -o`														# Присвоить переменной содержимое буфера обмена

if [[ -z `echo $clipboard | grep "youtu"` ]]
	then
		notify-send -t 10000 -i "gtk-error" "youtube-dl" "Буфер обмена не содержит ссылку на YouTube"
		exit
elif [[ `echo $clipboard | grep "https://"` ]]									# Корректировка ссылки. Добавить "https://"
	then url=$clipboard
	else url="https://"$clipboard
fi

link=${url/"›"/"/"}																		# Корректировка ссылки. Убрать символ ">"

# Вывод формы
parameters=`yad --focus-field=4 --borders=20 --width=600 --title="Youtube-dl" --text="Скачать видео" \
	--button="Скачать:0" \
	--button="Список форматов:5" \
	--button="Отмена:1" \
	--text-align=center --item-separator="|" --form \
	--field=" :LBL" --field="Ссылка:RO"			--field="Выбор качества:CB" 				--field="Каталог для сохранения:DIR" --field="Скачать только обложку:CHK" --field=" :LBL" --field="Скачать отрезок:LBL" --field="Начало (1:00):CE" --field="Длительность, сек" --field=" :LBL" \
		""				"$link"		"best|bestvideo|bestaudio|worst|worstvideo|worstaudio"			"${path_to_save}"						FLASE							""						""							""							10`

exit_status=$?

quality=$( echo $parameters | awk -F '|' '{print $3}')						# Выбор качества видео
dir=$( echo $parameters | awk -F '|' '{print $4}')								# Каталог для сохранения файла ($path_to_save)
thumbnail=$( echo $parameters | awk -F '|' '{print $5}')						# Скачать только обложку
start=$( echo $parameters | awk -F '|' '{print $8}')							# Время начала отрезка
duration=$( echo $parameters | awk -F '|' '{print $9}')						# Длительность

if [ "$exit_status" = 0 ]																# Закачка
   then
		if [ $thumbnail = TRUE ]														# Скачать только обложку
			then
				gnome-terminal --wait --title="youtube-dl" --geometry=80x10 --hide-menubar --working-directory="$dir" -- bash -c \
					"youtube-dl --console-title --write-thumbnail --skip-download --output \"${file_name1}\" $link; echo ; echo ------------------ ; echo \"Завершено\"; echo; read -p \"Нажмите ENTER чтобы закрыть окно\""
				
		elif [ -z $start ]
			then
				gnome-terminal --wait --title="youtube-dl" --geometry=80x10 --hide-menubar --working-directory="$dir" -- bash -c \
					"youtube-dl --console-title --continue --output \"${file_name1}\" --format $quality $link; echo; echo ------------------ ; echo \"Завершено\"; echo; read -p \"Нажмите ENTER чтобы закрыть окно\""
			else
				sufix="${start//:/-}_${duration//:/-}"
				file_name3=`youtube-dl --get-filename "$link"`
				youtube_url=$(youtube-dl -g --format $quality "$link" | sed "s/.*/-ss $start -i &/")

				if [[ `echo $quality | grep "audio"` ]]
					then
						gnome-terminal --wait --title="youtube-dl" --geometry=80x10 --hide-menubar --working-directory="$dir" -- bash -c \
							"ffmpeg -hide_banner -y $youtube_url -t $duration \"${file_name3}_$sufix.mp3\"; echo ; echo ------------------ ; echo \"Завершено\"; echo; read -p \"Нажмите ENTER чтобы закрыть окно\""
					else
						gnome-terminal --wait --title="youtube-dl" --geometry=80x10 --hide-menubar --working-directory="$dir" -- bash -c \
							"ffmpeg -hide_banner -y $youtube_url -t $duration -c copy \"${file_name3}_$sufix.mkv\"; echo ; echo ------------------ ; echo \"Завершено\"; echo; read -p \"Нажмите ENTER чтобы закрыть окно\""
				fi
		fi
fi

if [ "$exit_status" = 5 ]																# Получение списка и загрузка по коду
	then 
		gnome-terminal --wait --title="youtube-dl - $link" --geometry=120x26 --hide-menubar --working-directory="$dir" -- bash -c \
		"youtube-dl -F $link; echo; echo $link; echo; echo -n \"Введите format code для загрузки: \"; read format; echo; youtube-dl --console-title --continue --output $file_name2 --format \$format \"$link\"; echo ; echo ------------------ ; echo \"Завершено\"; echo; read -p \"Нажмите ENTER чтобы закрыть окно\""
fi
