#!/bin/bash

path_wtclient="$HOME/app/wtclient/wtclient"

# Проверка наличия утилиты wtclient
if [[ ! -a "${path_wtclient}" ]]
	then
		notify-send -t 10000 -i "error" "Отсутствует утилита wtclient" "Проверьте параметр path_wtclient"
		exit
fi

# Проверка права на исполнение утилиты wtclient
if [[ ! -x "${path_wtclient}" ]]
	then
		notify-send -t 10000 -i "error" "Файл wtclient присутствует, но файл не является исполняемым" "Сделайте исполняемым файл wtclient"
		exit
fi

first_element=$1														#Первый элементы переданный сценарию
path=$PWD																#Путь к элементам
timestamp=`date +%Y-%m-%d_%H-%M`									#Имя будущего архива по умолчанию


if [[ -d $first_element ]]												
	then archive_list="^zip|tgz|7z"								#Если выделен каталог предлагать только варианты с архивированием, т.к. wetransfer не поддерживает загрузку каталогов
	else archive_list="^нет|zip|tgz|7z"
fi

FORM=`yad --borders=10 --width=300 --title="Загрузка на Wetransfer" --text-align=center --text="Укажите параметры" --form --item-separator="|" --separator="," \
		--field=:LBL --field="Упаковать?:CB" --field="Имя архива:" --field="Пароль (только zip и 7z):" \
				"" 			"$archive_list" 			"$timestamp"						""`

if [ $? = 0 ]
	then
		packing=$( echo $FORM | awk -F ',' '{print $2}')
		name_archive=$( echo $FORM | awk -F ',' '{print $3}')
		full_name_archive="/tmp/${name_archive}"
		password=$( echo $FORM | awk -F ',' '{print $4}')
		
		if [[ "$packing" != "нет" ]]
			then	
				cd "$path"																												#Переходим в каталог с элементами (чтобы не сохранять полные пути)
				
				if [[ "$packing" = "zip" ]]
					then
						if [[ "$password" != "" ]]
							then archive=`zip -r -P "$password" "${full_name_archive}.zip" "${@##*/}"`				#Создаем архив zip с шифрованием
							else archive=`zip -r "${full_name_archive}.zip" "${@##*/}"`									#Создаем архив zip без шифрования
						fi
				fi
				
				if [[ "$packing" = "tgz" ]]
					then archive=`tar cfvz "${full_name_archive}.tgz" "${@##*/}"`										#Создаем архив tgz
				fi
				
				if [[ "$packing" = "7z" ]] 
					then
						if [[ "$password" != "" ]]											
							then archive=`7z a "${full_name_archive}.7z" "${@##*/}" -mx9 -mhe=on -p"$password"`	#Создаем архив 7z с шифрованием
							else archive=`7z a "${full_name_archive}.7z" "${@##*/}" -mx9`								#Создаем архив 7z без шифрования
						fi
				fi
				#notify-send -t 10000 -i "error" "Ошибка загрузки" "$archive"											#Отладка. Вывод результатов архивирования
				
				result=`"${path_wtclient}" upload "${full_name_archive}".*`
			else 
				result=`"${path_wtclient}" upload "$@"`
		fi
		
		link=`echo $result | awk '{print $5}' `

		if [[ `echo $link | grep "https://we.tl"` ]]																			#Проверка удачной загрузки
			then
				if [ "$password" != "" ] && [ "$packing" != "tgz" ]
					then
						echo -ne "$link\n$password" | xclip -i -selection clipboard										#Запись и пароля ссылки в буфер обмена
						notify-send -t 10000 -i "gtk-ok" "Загрузка на WeTransfer завершена" "Ссылка и пароль скопированы в буфер обмена"
					else
						echo -n "$link" | xclip -i -selection clipboard														#Запись ссылки в буфер обмена
						notify-send -t 10000 -i "gtk-ok" "Загрузка на WeTransfer завершена" "Ссылка скопирована в буфер обмена"
				fi
			else
				notify-send -t 10000 -i "error" "Ошибка загрузки" "$result"												#Вывод ошибки загрузки
		fi
fi