#!/bin/bash

list="$(printf " %q" "${@}")"

FORM=`yad --borders=10 --width=300 --title="Отправить через ssh" --text-align=center --text="Укажите параметры" --form --item-separator="|" --separator="," --field=:LBL --field="Имя:CBE" --field="IP адрес:CBE" --field="Каталог:CBE" "" "pi" "192.168.3.40" "|uni|pp"`

if [ $? = 0 ]
	then
		name=$( echo $FORM | awk -F ',' '{print $2}')
		ip_address=$( echo $FORM | awk -F ',' '{print $3}')
		folder=$( echo $FORM | awk -F ',' '{print $4}')
		gnome-terminal --hide-menubar -t "ssh" --geometry 110x30 -- bash -c "scp -r $list $name@$ip_address:$folder"
fi