#!/bin/bash

AAA=`yad --borders=10 --title="stl 2 png" --text="Создание изображения из stl" --text-align=center --form --item-separator="|" --field=:LBL --field="Ширина изображения" --field="Высота изображения" --field="Проекция:CB" --field="Автоцентровка:CHK" --field="Вписать модель в размер:CHK" --field="Камера авто:CHK" --field="Камера ручн." --field="              transx,transy,transz,rotx,roty,rotz,distance:LBL" "" 1080 1080  "ortho|perspective" TRUE TRUE TRUE "0,0,0,25,0,35,500"`

if [ $? = 0 ]
	then
		width=$( echo $AAA | awk -F '|' '{print $2}')
		height=$( echo $AAA | awk -F '|' '{print $3}')

		projection=$( echo $AAA | awk -F '|' '{print $4}')

		autocenter=$( echo $AAA | awk -F '|' '{print $5}')
		if [ $autocenter = "TRUE" ]; then autocenter='--autocenter'; else autocenter=''; fi

		viewall=$( echo $AAA | awk -F '|' '{print $6}')
		if [ $viewall = "TRUE" ]; then viewall='--viewall'; else viewall=''; fi

                camera_auto=$( echo $AAA | awk -F '|' '{print $7}')
                camera_man=$( echo $AAA | awk -F '|' '{print $8}')
                if [ "$camera_auto" != "TRUE" ]; then camera='--camera='${camera_man}; else camera=''; fi

                #Поиск файлов STL и формирование списка
                find "$1" -type f -iname "*.stl" -print0 | while read -d $'\0' file
                    do
                      #Имя файла без пути
                      filename="${file##*/}"

                      #Создаём временный файл scad с командой импорта stl
                      echo "import(\"${filename}\");" > "${file%.*}".scad

                      #Экспорт в png при помощи openSCAD
                      openscad -o "${file%.*}.png" $camera --projection=$projection $autocenter $viewall --imgsize=$width,$height "${file%.*}.scad"

                      #Удаление временного файла
                      rm "${file%.*}.scad"

                    done

                #Вывод уведомления
                notify-send -t 10000 -i "gtk-ok" "Завершено" "Создание файлов предварительного просмотра для STL"
fi
